name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip=22.2.2
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - pip:
    - albumentations==1.1.0
    - opencv-python==4.2.0.34
    - pudb==2019.2
    - pytorch-lightning==1.7.6
    - omegaconf==2.1.1
    - setuptools==59.5.0
    - pillow==9.4.0
    - einops==0.4.1
    - torch-fidelity==0.3.0
    - transformers==4.25.1
    - torchmetrics==0.11.1
    - captionizer==1.0.1
    - kornia==0.6.7
    - diffusers[training]==0.3.0
    - captionizer==1.0.1
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
